name: .NET

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./MonoGame.WpfControl/MonoGame.WpfControl.csproj
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./MonoGame.WpfControl/MonoGame.WpfControl.csproj
      
  publish:
    needs: build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./MonoGame.WpfControl/MonoGame.WpfControl.csproj
      
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nupkg ./MonoGame.WpfControl/MonoGame.WpfControl.csproj
    
    - name: Publish NuGet package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Publish NuGet package to nuget.org
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
